# Generated by Django 2.2.9 on 2021-03-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('aitvo', models.BooleanField(default=True)),
                ('popularidade', models.CharField(max_length=20)),
                ('prato', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Cardapio',
                'verbose_name_plural': 'Cardapios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Avalicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('aitvo', models.BooleanField(default=True)),
                ('popularidade', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(blank=True, default='')),
                ('criticas', models.TextField(blank=True, default='')),
                ('satisfacao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('avalicao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.Cardapio')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['prato'],
                'unique_together': {('email', 'prato')},
            },
        ),
    ]
