# Generated by Django 2.2.9 on 2021-03-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avalicacao',
            old_name='avalicao',
            new_name='avaliacao',
        ),
    ]
