# Generated by Django 2.2.9 on 2021-03-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210312_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='preço',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5),
        ),
    ]
