# Generated by Django 2.2.9 on 2021-03-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cardapio_preço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='url',
        ),
    ]
