# Generated by Django 2.2.9 on 2021-03-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cardapio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='preço',
            new_name='preco',
        ),
    ]
