# Generated by Django 2.2.9 on 2021-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210312_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
